title: Nertivia Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - category: Frontend
      name: Nertivia Stable Web App
      description: Application hosted at https://nertivia.net (stable).
    - name: Nertivia Beta Web App
      category: Frontend
      description: Application hosted at https://beta.nertivia.net (beta).
    - name: Nertivia CDN
      category: Backend
      description: Server hosting images uploaded to Nertivia.
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/transparentlogo.7f8e5f22.svg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Open Nertivia Stable
      link: https://nertivia.net/app
    - name: Open Nertivia Beta
      link: https://beta.nertivia.net/app
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Frontend
      description: Frontend Applications, such as the web apps.
      untitled: true
      closed: true
    - name: Backend
      description: Backend Applications, such as the CDN.
      closed: false
      untitled: true
  description: We continuously monitor the status of Nertivia's services and if
    there are any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
baseURL: https://stativia.netlify.app
